# Generated by Django 4.2.7 on 2023-12-05 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-value']},
        ),
        migrations.AddField(
            model_name='todolist',
            name='datetime_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
