# Generated by Django 4.2.7 on 2023-12-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todolist_options_todolist_datetime_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
