# Generated by Django 4.2.7 on 2023-12-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
