# Generated by Django 4.2.7 on 2023-12-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todolist_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='password',
            field=models.CharField(default='default_password', max_length=500),
        ),
    ]
